### ISSUE TITLE
Wrong method in Async page

### ISSUE THREAD

**Issue by euphocat** [grossbart/fp-ts-recipes#4]
Hello !

In the `Async ` page the `execute an array of tasks in parallel, collecting all failures and successes` given is: `array.sequence(TE.taskEither)(taskEithers)` which I think is wrong according to https://github.com/gcanti/fp-ts/issues/995

If you like I could provide a PR to fix it :)

**Comment by grossbart** [comment]
Hi Nicolas,

It would be great if you could create a PR for this! If I understand correctly, your requirement is slightly different than what's currently in the table, so I think it would make sense to add this as an alternative. Not 100% sure I understand it correctly, though, hence why I'd be happy for your PR :)

**Comment by rjhilgefort** [comment]
Sorry to revive an old thread but I don't think the updated docs for `allSettled` are correct? I tried `A.sequence(TE.task)(taskEithers)` or `A.sequence(T.ApplicativePar)(taskEithers)` but the types aren't happy. Do I need to convert all the TEs to Ts first?

**Comment by THOUSAND-SKY** [comment]
@rjhilgefort I also ran into that. Asked here: https://github.com/gcanti/fp-ts/discussions/1754 . Don't know about your specific case, but for me the types started complaining in my simple test, which left me confused:

```
await pipe(
      [1, 2, 3, 4],
      array.map((x) =>
        x > 2 ? taskEither.left(x) : taskEither.right(x)
      ),
      array.sequence(task.ApplicativePar),
    )()
```

But then it works once I type the `taskEither.left` to `taskEither.left<number, number>(x)`. Moral of the story might be to ignore type errors when doing trial and error, and just run it instead.
