### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by Schokokex** [grossbart/fp-ts-recipes#5]
I find it hard(er) to learn fp-ts with all the Abbreviations... ([hint to wikipedia](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Readability))

for example: i thought `E` meant `Error`:
```typescript
fetchGreeting()
  .then(e =>
    pipe(
      e,
      E.fold(
        err => `I'm sorry, I don't know who you are. (${err.message})`,
        x => `Hello, ${x.name}!`
      )
    )
  )
  .then(console.log);
```

It might be intiutive for confident users, but id suggest to just use the Import names (`Either` instead of `E`).

Still this is a great resource for learning!

**Comment by grossbart** [comment]
You're right, this is a small change that might make things a bit easier – I'll have a look at this and your PR in the coming days, thanks!
